import { CABIN_SLUGS } from '../../../core/utils/reviews';

export interface GuestReview {
  id: string;
  cabinSlug: string;
  guestName: string;
  stayLabel: string;
  rating: number;
  quote: string;
  source: 'Airbnb';
  avatarUrl: string;
}

function review(
  id: string,
  cabinSlug: string,
  guestName: string,
  stayLabel: string,
  quote: string,
  rating = 5,
): GuestReview {
  return {
    id,
    cabinSlug,
    guestName,
    stayLabel,
    rating,
    quote,
    source: 'Airbnb',
    avatarUrl: `/reviews/avatars/${id}.jpg`,
  };
}

const { blackGum, dogwood, runningSpring, blackWalnut, whiteOak, postOak } = CABIN_SLUGS;

export const GUEST_REVIEWS: GuestReview[] = [
  review(
    '6-04-58',
    postOak,
    'Xaine',
    'July 27–29 · 2 nights',
    'Our stay was great! The place was very cozy and nice! I loved the dogs! They got along great with my dog as well! Definitely will be coming back!',
  ),
  review(
    '6-06-53',
    postOak,
    'Lorna',
    'July 24–26 · 2 nights',
    'We really enjoyed our stay! Such a beautiful place and Jeff was amazing, great directions, recommendations, and a wonderful home.',
  ),
  review(
    '6-07-34',
    postOak,
    'Tommy',
    'July 22–24 · 2 nights',
    'Cool spot, beautiful wooded rear view.',
  ),
  review(
    '6-08-54',
    postOak,
    'Jordan',
    'July 10–12 · 2 nights',
    'Couldn’t recommend this place more! 11/10.\n\nNot only is it clean, peaceful, and beautiful, it feels like a piece of home and is well built! Sweet dogs too. Also, Jeff is definitely the kind of guy you want to be your host!',
  ),
  review(
    '6-11-50',
    postOak,
    'Dakota',
    'March 27–29 · 2 nights',
    'This place was perfect! We wanted a quiet, modern place that allowed pets and that was exactly what we got! The place was just like the photos, the woods were beautiful to wake up to, and the place was super clean and welcoming. We had everything that we needed! We loved the location and drove a short 20 minute drive into Bentonville a couple times. Jeff gave us recommendations on places to take our dog and was very responsive. We already talked about going back before we even left!',
  ),
  review(
    '6-12-40',
    postOak,
    'Daniel',
    'March 26–27 · 1 night',
    'on a 3k mile road trip over a week, this was the most pristine and aestheticly pleasing place we stayed along the way. if I could offer more than 5 stars, I would.',
  ),
  review(
    '6-13-39',
    postOak,
    'Sarah',
    'September 25–28, 2025 · 3 nights',
    'We plan on staying here again anytime we’re in the area! Why would we stay anywhere else? It’s conveniently located with beautiful scenery and so cute! We have also already recommended it to several friends.',
  ),
  review(
    '6-14-46',
    postOak,
    'Alyssa',
    'December 12–14, 2025 · 2 nights',
    'This location is a hidden gem when looking for places to stay in NW AR! We went in the winter and found that the unit stays warm and inviting. Jeff had given clear instructions on how to get to the location and checked in appropriately with us. We will be looking at staying here again!',
  ),
  review(
    '6-16-31',
    postOak,
    'Jennifer',
    'January 11–13 · 2 nights',
    'Beautiful peaceful place. Would definitely stay again.',
  ),
  review(
    '6-17-41',
    postOak,
    'Sara',
    'January 18–20 · 2 nights',
    'Great cabin! It was so clean and nice. We especially loved the wooded view from the back deck and the coziness and being close to town.\n\nDouble points for the sweet dog!',
  ),
  review(
    '6-19-01',
    whiteOak,
    'Megan',
    'July 30–August 1 · 2 nights',
    'We had a wonderful stay at Jeff’s A-Frame cabins. They are beautifully designed and Jeff was a gracious host. The cabin was spotless and we had everything we needed for a relaxing getaway. The peaceful setting made it the perfect place to unwind. We would absolutely stay here again and highly recommend it to anyone looking for a cozy escape in Arkansas!',
  ),
  review(
    '6-19-58',
    whiteOak,
    'Desiree',
    'July 23–25 · 2 nights',
    'Our stay was wonderful. The cabin looks exactly like the pictures; peaceful and serene. It was perfectly located to quickly get to Bentonville, Rogers, and Beaver Lake. Our family of 4 had plenty of room to sleep and watch tv in the living room. The WiFi connection was strong enough for me to work from too. We would definitely stay again!',
  ),
  review(
    '6-21-09',
    whiteOak,
    'Christy',
    'July 2–3 · 1 night',
    'The cabin was adorable! Clean, easy check-in and out. Will definitely stay there again!',
  ),
  review(
    '6-21-39',
    whiteOak,
    'Macy',
    'March 21–23 · 2 nights',
    'Such a beautiful place to stay!! Looking forward to going back in the fall to see the leaves change!! The dogs on property were so friendly an happy! Perfect weekend getaway. Close to town but far enough away for peace!',
  ),
  review(
    '6-22-24',
    whiteOak,
    'Ariadne',
    'March 15–19 · 4 nights',
    'We LOVED our stay here! Stayed for 4 nights with our 2 kids and it felt so cozy and inviting. Such a lovely aesthetic...really appreciated the build. Just a true gem. The dogs Roger and Otis who roam the property were such a pleasure to watch and play with. Kids said it was one of their favorite stays! There are 5 other cabins just like it so grab your friends and family and stay here!',
  ),
  review(
    '6-23-30',
    whiteOak,
    'Avery',
    'February 13–15 · 2 nights',
    'Stayed at this cabin with my husband for a weekend trip and we had the best stay! The cabin is a unique build and we loved the layout of it. It’s cozy and peaceful. We were just a short drive from Rogers which made outings easily doable. We were greeted by dogs when we arrived and they were very sweet! Jeff was very communicative and made sure we were enjoying our stay. We had an amazing time and would definitely recommend this place!',
  ),
  review(
    '6-24-39',
    whiteOak,
    'Ryan',
    'December 12–14, 2025 · 2 nights',
    'Beautiful cabins, thoughtfully designed. Private and peaceful location within a good distance to Roger’s. Jeff communicated great and we had all we needed.',
  ),
  review(
    '6-24-55',
    whiteOak,
    'Jay',
    'November 21–23, 2025 · 2 nights',
    'I took my daughter and our dog for a relaxing weekend trip to Jeff’s place. My dog loved running around the property with his two dogs while my daughter and I hiked around the woods. It was a memorable weekend away. 10/10 would recommend.',
  ),
  review(
    '6-25-30',
    whiteOak,
    'Ashley',
    'September 26–28, 2025 · 2 nights',
    'Our family enjoyed our stay so much! We played in Rogers, Eureka and went to a razorback game! Great location',
  ),
  review(
    '6-27-33',
    blackGum,
    'Cody',
    'August 5–6 · 1 night',
    'One of the nicest places I’ve stayed in.',
  ),
  review(
    '6-28-03',
    blackGum,
    'Jim',
    'July 31–August 1 · 1 night',
    'I would highly recommend this cabin for anyone who wants to get away, relax, and enjoy the scenery.',
  ),
  review(
    '6-29-31',
    blackGum,
    'Alex',
    'July 3–7 · 4 nights',
    'Everything regarding the home was well done. It is well designed and appealing. The location of the property is peaceful and quiet, with the communal aspects of the property being nice touches. We especially enjoyed the friendly dogs that roamed the property. I would not hesitate to recommend the property.',
  ),
  review(
    '6-30-30',
    blackGum,
    'Dianna',
    'June 19–21 · 2 nights',
    'Jeff\'s place is exactly as described and shown in the pictures. Beautiful home with custom woodwork for the A-Frame home and cedar planks on the back porch. It was perfect for yoga each morning. Fireflies at night and birdsong every morning. Close to down Rogers and Lake Atalanta that has a nice paved bike trail for waking or a short bike ride, but also easy access to the Razorback Greenway there. We went to 2 different Farmer\'s Markets and then cooked our meals and relaxed. Loved it.',
  ),
  review(
    '6-31-22',
    blackGum,
    'Daniel',
    'June 12–14 · 2 nights',
    'Beautiful space nestled in the woods behind a little community. Was everything listed and more. The grill space was very nice and the peach trees smell amazing, especially after the rain.',
  ),
  review(
    '6-32-09',
    blackGum,
    'Christian',
    'May 25–26 · 1 night',
    'Honestly such a beautiful cabin and spot, close to the city but also feels very secluded. Absolutely loved it!',
  ),
  review(
    '6-33-51',
    blackGum,
    'Erica',
    'April 17–19 · 2 nights',
    'This home was beautiful, it was very clean, the bed upstairs was comfy and we slept so well. There’s a balcony out the back that looks over a beautiful wooded area. We were able to relax and enjoy the peace and quiet while there. We will stay again in the future!',
  ),
  review(
    '6-32-46',
    blackGum,
    'Billy',
    'May 21–22 · 1 night',
    'I am about to be checking out this morning and they’re going to need to come and drag me out of here. Absolutely recommend this stay and will be returning asap!',
  ),
  review(
    '6-34-40',
    blackGum,
    'Ana',
    'February 27–March 1 · 2 nights',
    'This place was amazing. We were so impressed by how clean & private it felt. Absolutely loved the dogs on the property, they are great with people and loved my little bernadoodle Roni. 10/10 recommend and hope to be back.',
  ),
  review(
    '6-37-11',
    blackGum,
    'Erick',
    'November 26–28, 2025 · 2 nights',
    'Very nice and cozy modern cabin. It has everything you need for a small family. It’s a quiet place, surrounded by nature. The owner is very responsive.',
  ),
  review(
    '6-38-52',
    blackGum,
    'Travis',
    'October 2–5, 2025 · 3 nights',
    'Jeff was incredible with prompt communication. Everything there was just as described. Beautiful location that is private yet still not far from town. Clean and spotless and very accommodating. Will definitely be staying here again when I’m in town.',
  ),
  review(
    '6-39-46',
    blackGum,
    'Evan',
    'January 10–11 · 1 night',
    'We really enjoyed our stay, the cabin had a lot of style and felt very cozy and modern.',
  ),
  review(
    '6-41-16',
    blackWalnut,
    'Amanda',
    'August 2–3 · 1 night',
    'What a special place - we didn’t want to leave! First, it’s so nice to see a place like this that has two real beds, it was perfect for us and our teenager. The scenery off the back porch was like the enchanted forest. We spent a lot of time out there just sitting. The whole place was super clean, really well appointed and felt luxurious but also comfortable.',
  ),
  review(
    '6-42-06',
    blackWalnut,
    'Destan',
    'July 16–18 · 2 nights',
    'Perfect secluded cabin in the Rogers/ Bentonville area. Lots of character built into this well-appointed space.',
  ),
  review(
    '6-42-53',
    blackWalnut,
    'Sabrina',
    'June 28–29 · 1 night',
    'The most peaceful time was had in the beautiful cabin surrounded by trees. The place is stunning.',
  ),
  review(
    '6-43-37',
    blackWalnut,
    'Isabella',
    'June 5–7 · 2 nights',
    'What a LOVELY stay! This place was beautiful, clean, & relaxing beyond belief. I cannot emphasize how lovely the cabins are—you can tell they are well-built & so tastefully decorated! The natural surroundings were so beautiful & it was genuinely just a wonderful experience. Jeff was a great host & I look forward to returning.',
  ),
  review(
    '6-44-19',
    blackWalnut,
    'Alandrea',
    'May 29–31 · 2 nights',
    'The cabin is beautiful. I loved the balcony facing the trees. The dogs greeted us as we arrive which started the trip off great. My stay was cozy and quiet.',
  ),
  review(
    '6-46-10',
    blackWalnut,
    'Becky',
    'May 16–19 · 3 nights',
    'Clean and cozy! Even with the other cabins around it felt very secluded. :)',
  ),
  review(
    '6-47-15',
    blackWalnut,
    'Jennifer',
    'April 30–May 1 · 1 night',
    'This is the perfect place to get away and unplug from the pressures of a busy life. The host was friendly and very responsive to messages. The cabin was well arranged to maximize the space and reflect the outdoors. The scenery was absolutely beautiful! This is a spot I look forward to returning to in the future.',
  ),
  review(
    '6-47-59',
    blackWalnut,
    'Paul',
    'March 23–24 · 1 night',
    'Most unique beautiful BNB I\'ve ever stayed in!',
  ),
  review(
    '6-48-36',
    blackWalnut,
    'Justin',
    'March 18–21 · 3 nights',
    'This place is an absolute gem. Rent it while you can....it will be full all the time. Gorgeous property and even better A-frame. Feels so private and peaceful, but not far from town. Jeff is an amazing host. He has something special on his hands!',
  ),
  review(
    '6-49-34',
    blackWalnut,
    'Jessie',
    'February 26–28 · 2 nights',
    'Absolutely AMAZING stay! The perfect weekend getaway for my partner and I.\n\nWe plan on booking again for a weekend trip in April!',
  ),
  review(
    '6-50-34',
    blackWalnut,
    'Sean',
    'December 31, 2025–January 2, 2026 · 2 nights',
    'Excellent place to stay and relax!',
  ),
  review(
    '6-51-36',
    blackWalnut,
    'Htet',
    'November 29–December 1, 2025 · 2 nights',
    'Holy moly this was one of the best places I’ve stayed at. The home was very clean, easy to find, and easy to get in. I was afraid it was going to be small but it was actually very spacious. I did hit the wall up stairs once but that was my fault haha. We came from Texas for a wedding but only stayed 2 nights, I’ll definitely be back to fully enjoy it!',
  ),
  review(
    '6-53-42',
    blackWalnut,
    'Ben',
    'October 10–12, 2025 · 2 nights',
    'Great location. Minutes from downtown Rogers and on the doorstep of downtown Bentonville. We will be back',
  ),
  review(
    '6-55-44',
    dogwood,
    'Kathryn',
    'August 3–5 · 2 nights',
    'This airbnb was so beautiful and peaceful! A great setting with just a short gravel drive to get there. Such a cool interior with gorgeous woods out the back. We loved all the windows and the decor matched so well with the whole vibe. Jeff was helpful and communicative with any questions we had!',
  ),
  review(
    '6-56-29',
    dogwood,
    'Somyr',
    'July 17–18 · 1 night',
    'Beautiful and unique cabin. Close to everything. Nestled perfectly in the woods which makes it peaceful',
  ),
  review(
    '6-58-03',
    dogwood,
    'Gaby',
    'May 23–25 · 2 nights',
    'Absolutely breathtaking cabin experience! Every detail was stunning — from the luxurious cozy interior to the beautiful rustic touches that made it feel straight out of a dream. The atmosphere was peaceful, elegant, and incredibly relaxing. Truly one of the most beautiful and unforgettable stays ever!',
  ),
  review(
    '6-59-09',
    dogwood,
    'Chandler',
    'May 21–22 · 1 night',
    'We had a great stay! The cabin is very well taken care of and extremely clean! We enjoyed a quiet night away and spent most of our time on the back deck. Beautiful place!',
  ),
  review(
    '6-59-45',
    dogwood,
    'Alejandra',
    'April 24–26 · 2 nights',
    'This place was amazing it had everything we needed! So cozy, clean, and beautiful. We loved how peaceful it was. The host was also super accommodating with a late checkout, which we really appreciated. We enjoyed our stay and will definitely be back!',
  ),
  review(
    '7-00-14',
    dogwood,
    'Alex',
    'March 29–April 7 · 9 nights',
    'Beautiful place! Highly recommend',
  ),
  review(
    '7-00-46',
    dogwood,
    'Mariana',
    'March 17–20 · 3 nights',
    'My family and I had a great time. The cabin was comfortable, clean, and cozy and had everything we needed. The kids really enjoyed walking around the property and the dogs were the sweetest tour guides. Will definitely be back.',
  ),
  review(
    '7-01-22',
    dogwood,
    'Sunny',
    'March 13–16 · 3 nights',
    'Great peaceful place to stay. We can tell they put a lot of thought into building and decorating the place. The beds, blankets, pillows were are really comfortable and our kids really enjoyed the room they slept in. Loved that they provided coffee (Keurig) and creamer too. Really enjoyed our stay.',
  ),
  review(
    '7-02-02',
    dogwood,
    'Laney',
    'January 23–25 · 2 nights',
    'What a beautiful location! We got to cuddle up and watch the snow fall. It was beautiful, cozy, clean, and Jeff was great!',
  ),
  review(
    '7-03-03',
    dogwood,
    'Natalie',
    'November 27–29, 2025 · 2 nights',
    'Absolutely loved our stay at this cabin. It was spotless, cozy, and exactly as described. The views were beautiful, and the host was responsive and helpful. We especially enjoyed the quiet surroundings and the thoughtful touches throughout the space. Would definitely stay again!',
  ),
  review(
    '7-05-04',
    runningSpring,
    'Larry',
    'July 23–24 · 1 night',
    'This was an absolute spectacular stay and easily one of my favorite Airbnbs. The cabin is gorgeous, the views are incredible, and everything is brand new and spotless.\n\nSitting on the deck overlooking the trees felt like hitting life\'s reset button. It was peaceful, quiet, and exactly what we needed.',
  ),
  review(
    '7-06-16',
    runningSpring,
    'Janell',
    'June 22–24 · 2 nights',
    'We had a wonderful stay at this cozy A-frame cabin. Everything was exactly as described, and the cabin was clean, comfortable, and tucked away in the peaceful woods. Jeff was a great host and made everything easy from start to finish. We loved the quiet surroundings and the chance to truly relax. We would definitely stay here again and look forward to coming back!',
  ),
  review(
    '7-06-54',
    runningSpring,
    'Lacey',
    'May 27–30 · 3 nights',
    'Amazing stay! Beautiful location and a great host.',
  ),
  review(
    '7-07-28',
    runningSpring,
    'Chris',
    'May 22–24 · 2 nights',
    'Great location and pristine cabins. Felt isolated and away from civilization, but only 10 minutes from Rogers and 15 to 20 minutes from Bentonville. Beautiful little secluded area. Great for a couples weekend getaway, and would also be ideal for multiple families, each wanting their own private abode.',
  ),
  review(
    '7-08-59',
    runningSpring,
    'Pamela',
    'April 24–26 · 2 nights',
    'Beautiful little cabin tucked away into the woods but a quick ten minute drive to downtown Rogers! Loved how quiet and beautiful the view out of the back windows were. The place was exactly as described and very comfortable.',
  ),
  review(
    '7-09-43',
    runningSpring,
    'Matt',
    'April 1–3 · 2 nights',
    'This A Frame was one of the most unique Air BnB\'s I have stayed in. It was beautiful inside and made for a very relaxing atmosphere for our trip. I couldn\'t recommend it more. Definitely worth the trip!',
  ),
  review(
    '7-10-29',
    runningSpring,
    'Meredith',
    'March 14–17 · 3 nights',
    'Our family of 4 enjoyed a long weekend at one of the cabins. The cabin was beautifully decorated and had everything we needed. The property is peaceful and beautiful. The space was perfect for me, my husband and our 2 young kids (ages 5 and 7) who loved exploring the property and especially loved the 2 dogs on the property. Jeff was a great host. It was a great place to stay while visiting the area. We would definitely recommend and would love to stay here again.',
  ),
  review(
    '7-11-42',
    runningSpring,
    'Cody',
    'February 6–8 · 2 nights',
    'My wife and I had the weekend to ourselves here and loved it! Beautiful location and beautiful cabin! It was perfect for just the two of us. Far enough out of Rogers to be secluded but still close enough to do all the things in the city. Would definitely stay again!',
  ),
  review(
    '7-12-59',
    runningSpring,
    'Alejandro',
    'January 1–4 · 3 nights',
    'If you\'re someone who wants to escape the city & have some alone time with friends, partner or family, this is for you! You are a short drive to a beautiful lake to enjoy the sunset & an amazing downtown to enjoy some bagels & coffee! Our stay was warm, cozy & inviting! Beautifully designed & built cabin with clean sheets and towels & as well as all the kitchen appliances you need to make it a great stay with your loved ones! The host is very kind, I will definitely be returning!',
  ),
  review(
    '7-13-31',
    runningSpring,
    'Joseph',
    'November 26–29, 2025 · 3 nights',
    'So well appointed. This is the perfect place if you\'re trying to retreat solo or with a few friends. So serene and ideal and peaceful.',
  ),
  review(
    '7-14-02',
    runningSpring,
    'Ashley',
    'October 24–26, 2025 · 2 nights',
    'Would absolutely recommend and will likely stay again. Extremely clean and fresh. Looks exactly like the pics. Not far from anything. Well stocked kitchen. Can\'t say enough good things!',
  ),
  review(
    '7-14-55',
    runningSpring,
    'Carsyn',
    'September 26–28, 2025 · 2 nights',
    'This cabin was the perfect getaway! It\'s cozy, peaceful, and surrounded by nature, making it such a relaxing stay. Everything was clean, well-kept, and exactly as described. The host was wonderful, very friendly and quick to respond to any questions, which made the whole experience even better. If you\'re looking for a quiet place to unwind with beautiful views, this is definitely the spot. Highly recommend!',
  ),
];

export function reviewsForCabin(slug: string): GuestReview[] {
  return GUEST_REVIEWS.filter((reviewItem) => reviewItem.cabinSlug === slug);
}
